### ISSUE TITLE
[Bug] Microsoft Excel is loosing menu and ribbon bar

### ISSUE THREAD

**Issue by s-v-o** [glzr-io/glazewm#250]
I have a strange behaviour with Microsoft Excel.
  
When I start Excel, everything is fine: 
![image](https://user-images.githubusercontent.com/64085779/218489672-051c14dc-6047-4e3f-9e9f-3d93746ce68f.png)
  
After changing the workspace and comming back the menu and ribbon bar disappear:
![image](https://user-images.githubusercontent.com/64085779/218489964-97348b8d-8b9e-4b93-bce5-8c6ea1ef4f52.png)
  
Even stranger: Everything works fine in Word.
  
I cannot say excactly in which version of GlazeWM I first noticed this.

There are no new entries in errors.log.

**Comment by CalvinTrop** [comment]
Same issue here, which unfortunately renders the project unusable for my current workflow...

**Comment by kirpy0x** [comment]
Same here on Win11.  If I remember correctly, this didn't happen on Win10.

I thought it was an issue with my Excel Installation but then noticed they all disappeared right once a Window management action was done.

**Comment by rwijtvliet** [comment]
Same here. FWIW, I'm on Win10 enterprise edition.

**Comment by hongyuanjia** [comment]
Same here. I'm on Win 10 Pro 22H2. Word and PowerPoint work perfectly fine.

**Comment by AttackOnTyler** [comment]
Can confirm, Toggling full screen doesn't remedy the issue either.

**Comment by s-v-o** [comment]
FWIW: As a workaround I've added this to my config.yaml:
```
- command: "ignore"
  match_title: "/Excel/"
```
So Excel is ignored from GlazeWM and I could use it. But of course this way Excel is not managed by GlazeWM.

**Comment by n-crespo** [comment]
Here to add another barely useful nugget of information. I'm having this exact problem, here's how I'm forcing it to work for my workflow. 

I have a few apps that I want Glaze to ignore, (they will appear in every workspace, keymaps don't work on them, etc) and one of those is PowerToys, because I use PowerToys Run to launch applications easily  (With the exception of my browsers/terminal/Spotify which I launch with Glaze keymaps) and I don't want Glaze to get confused by the popups and other tools.

Basically, I decided to take advantage of the fact that Glaze doesn't work with Windows' Virtual Desktops, meaning when I switch desktops Glaze still works, but the workspaces I made in the previous desktop are not accessible in the new one. To make desktop switching easier, I used PowerToys' "Keyboard Manager" to map <alt+,> and <alt+.> for switching between virtual desktops. 

![image](https://github.com/glazerdesktop/GlazeWM/assets/122305393/f45ef7e2-5965-4092-ac9b-e482f5308ac5)

This way I can keep my regular workflow in the main virtual desktop with all my Glaze workspaces, and have any "ignored" applications in another virtual desktop that I can switch to whenever I want. Obviously, this is not a true solution, and I definitely spent way too much time writing this but hopefully someone will find it semi-useful. 

NOTE: For some reason, the four finger swipe to change workspaces stopped working for me whenever Glaze is running, but using a keymap works better for me anyways.

**Comment by Contrabass26** [comment]
I get two different windows when I open a workbook...

![Screenshot 2024-04-14 151338](https://github.com/glzr-io/glazewm/assets/83555891/d52b9e00-c3a5-41d0-b410-c5a3b3c82257)

Then after switching workspaces the ribbon disappears as others have said.

**Comment by LJFRIESE** [comment]
+1 on this still being an issue. Super frustrating. As soon as glaze interacts with the excel window, the ribbon is gone.

**Comment by s-v-o** [comment]
The rust rewrite is also affected (preview version) (#604)

**Comment by LJFRIESE** [comment]
I believe this issue has been identified in other window-management software. This discussion might provide useful information: https://answers.microsoft.com/en-us/msoffice/forum/all/excel-ribbon-disappearing-when-switching-virtual/8fe6fa89-7b96-439e-aa6b-0ae5f6b9c275

Haven't worked out how to apply it to glaze.

**Comment by superwhoopy** [comment]
To get the ribbon back quickly, you can type `<C-o><Esc>`: it opens the "Open" menu (`<C-o>`) then closes it (`<Esc>`). For some reason, Excel re-draws the ribbon in that scenario.

Not exactly a workaround, but at least you don't have to close/re-launch Excel every time… 😒

**Comment by LJFRIESE** [comment]
Oh geeze, thank you! That worked an is good enough for now, honestly. I was losing my mind.

**Comment by alyraecap** [comment]
In case newbs like me didn't understand superwhoopy's solution at first, it's Ctrl-O then Esc in Excel for regular Windows users.

**Comment by rmanthorpe** [comment]
This issue is resolved with #792 released in v3.6!

**Comment by alyraecap** [comment]
I can confirm too it's finally fixed!

**Comment by t-clement1** [comment]
I just installed the software, and it's not fixed on my end. ctrl+o does not fix it either.

<img width="1919" height="1079" alt="Image" src="https://github.com/user-attachments/assets/7a154595-ab4e-4e8d-9bb6-0e19153e9e9f" />

<img width="1919" height="1079" alt="Image" src="https://github.com/user-attachments/assets/91001bad-82c0-4679-800c-b36cae977077" />

**Comment by PumaFPV** [comment]
I am running GlazeWM 3.9.1 and I still have this issue on windows 10 and 11, ctrl+O ESC works to fix it though...

**Comment by PumaFPV** [comment]
For info ctrl+O Esc doesnt work anymore
