### ISSUE TITLE
[BUG] Preventing the display to turn off in lock screen

### ISSUE THREAD

**Issue by kimagin** [glzr-io/glazewm#518]
### Normal behavior

When you hit **win+L** or manually lock windows 11, the default behavior is to turn of the screen after about 30 seconds. This is particularly important for the desktop users with an **OLED** display as the background is static and it can destroy the hardware.

### The issue

While **GlazeWM** is running, if the user lock the window, after about 30 seconds, the screen turns black for a brief moment, but it loops back into the login screen. This infinit loop, prevents the screen to go to sleep mode.

### Temporary solution

If you simply turn off **GlazeWM** by right clicking on the taskbar icons or via windows task manager, the issue will be resolved and the screen behaves as it should.

**Comment by Garulf** [comment]
I am noticing this behavior as well. Windows 11

**Comment by lars-berger** [comment]
Fixed in the latest [v2.1.1 release](https://github.com/glzr-io/glazewm/releases) 🎉

**Comment by katawajojo** [comment]
Can we open this back up? This issue is still occurring with a fresh install.

Happening here, Windows 11, multiple monitors.

**Comment by Kirupakaran** [comment]
Same here, W11. I have an external monitor connected to a laptop. Laptop refuses to go to sleep even if the external monitor is powered off. I have to manually kill glazewm.

**Comment by txj-xyz** [comment]
This just happened to me about 11 times today at work.


Windows 11 22H2 + Windows 11 22H3 VM (VMWare Workstation Pro 17)

**Comment by txj-xyz** [comment]
Since my last reply, I just came into the office, both my laptop + second monitor were off.

CPU Usage was around 85% on idle from GlazeWM, once I rebooted the program everything was OK except all my window positions and layouts

**Comment by AfzGit** [comment]
Noticing it here as well on Windows 11 23H2.

**Comment by thespeck** [comment]
Issue is very much unfixed. Screen is turning off momentarily, just to wake up right after. And lock screen only shows the wallpaper, no text with it. I'm using it on Windows 11 23H2 too.

**Comment by AfzGit** [comment]
@thespeck The project is currently under a re-write so don't expect it to be fixed soon.

https://github.com/glzr-io/glazewm/issues/604

**Comment by thespeck** [comment]
I think I found a solution for this bug. GlazeWM should ignore Windows lock screen and not try to manage it. Adding the following lines to `%USERPROFILE%\.glaze-wm\config.yaml` should fix the problem.

```yaml
window_rules:
  # Windows Lock Screen should be ignored.
  - command: "ignore"
    match_process_name: "/LockApp/"
```

**Comment by AfzGit** [comment]
> I think I found a solution for this bug. GlazeWM should ignore Windows lock screen and not try to manage it. Adding the following lines to `%USERPROFILE%\.glaze-wm\config.yaml` should fix the problem.
> 
> ```yaml
> window_rules:
>   # Windows Lock Screen should be ignored.
>   - command: "ignore"
>     match_process_name: "/LockApp/"
> ```

Works! Had to add this and then restart my PC. This looks like something that needs to be added in by default in the config YAML.

**Comment by lars-berger** [comment]
> I think I found a solution for this bug. GlazeWM should ignore Windows lock screen and not try to manage it. Adding the following lines to `%USERPROFILE%\.glaze-wm\config.yaml` should fix the problem.
> 
> ```yaml
> window_rules:
>   # Windows Lock Screen should be ignored.
>   - command: "ignore"
>     match_process_name: "/LockApp/"
> ```

Thanks for sharing this btw 🙌 It's been added as a built-in rule in v3
